In [2]:
import numpy as np
np.__version__

'1.22.2'

An integer in python is basically a data structure created in the language C. 
Which means when an integer is declared in python, it links multiple other informations to this integer with it.
i.e. the size needed to store the integer. the memory allocated to store the variable, the data type of the variable.


A Python list can, unlike lists in other programing languages, store multiple data type objects simultaneously. This means each entry in such a list is an object in itself. even if we have the list filled with the same data type objects, much of the information would be redundant.

That's why we have Numpy lists with fixed data types.

# Creating Numpy Array


Simple way of creating a numpy array. Can drop the dtype attribute

In [3]:
np.array([i for i in range(1,11,2)],dtype='float64')

array([1., 3., 5., 7., 9.])

Multi-dimensional lists also exist

In [4]:
multidim=np.array([list(range(i,i+5)) for i in range(1,5)])

In [5]:
print(multidim)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


# Easy shortcuts to create and array

In [6]:
zeroarray2by2=np.zeros(2)
zeroarray2by3=np.zeros((2,3))
print(zeroarray2by2)
print(zeroarray2by3)

[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
onesarray2by2=np.ones(2)
onesarray2by3=np.ones((2,3))
print(onesarray2by2)
print(onesarray2by3)

[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
sameintegerarray=np.full((2,3),6.5)
print(sameintegerarray)

[[6.5 6.5 6.5]
 [6.5 6.5 6.5]]


In [9]:
similartorange=np.arange(1,11,2)
similartorange2=np.arange(1,12,2)

print(similartorange)
print(similartorange2)

[1 3 5 7 9]
[ 1  3  5  7  9 11]


In [10]:
equallyspacedvalues=np.linspace(2,200,10)#Inclusive of both the endpoints
print(equallyspacedvalues)

[  2.  24.  46.  68.  90. 112. 134. 156. 178. 200.]


In [11]:
random3dimensionalarray=np.random.random((4,3,2))
print(random3dimensionalarray)

[[[0.14277587 0.4834854 ]
  [0.43480918 0.43179257]
  [0.38395378 0.72871493]]

 [[0.87451215 0.53334754]
  [0.50149853 0.74825499]
  [0.95376918 0.19091411]]

 [[0.7032876  0.96640639]
  [0.36156799 0.25085819]
  [0.70359506 0.29759033]]

 [[0.27308511 0.10765974]
  [0.27227052 0.9495659 ]
  [0.53944433 0.06247192]]]


In [12]:
normallydistributed3dimensionalarray=np.random.normal(10,3,(3,3,3))
print(normallydistributed3dimensionalarray)

[[[ 9.71120073  4.25196267 15.04805   ]
  [11.50174478 11.2292895  12.44851984]
  [10.54950675  9.17945278 12.16991568]]

 [[ 9.94719029 11.35639775  5.17540249]
  [10.54935513 10.53479609 13.86382082]
  [15.58692641  9.22623361  8.87274097]]

 [[13.90069268  8.22682948 10.49732363]
  [ 7.41216565 15.18535973  8.90507302]
  [ 6.56789054 13.96856602  9.45178536]]]


In [13]:
randomint4_3_2dimensionalarray=np.random.randint(5,500,(4,3,2))
print(randomint4_3_2dimensionalarray)

[[[469 148]
  [406 182]
  [360  91]]

 [[159 112]
  [124 248]
  [ 85 299]]

 [[ 89  45]
  [477 315]
  [ 92 464]]

 [[249  94]
  [380 127]
  [141 373]]]


In [14]:
identitymatrixsortof=np.eye(5,6,2)
print(identitymatrixsortof)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
uninitializedarray=np.empty(3)
#the values will be whatever exist in the locatiaon already
print(uninitializedarray)


[7.74860419e-304 7.74860419e-304 7.74860419e-304]


In [16]:
np.zeros((10,2),dtype='int16')

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

There exist many types of datatypes of numpy arrays which one can look up.