In [2]:
import numpy as np

# Numpy Array Manipulation

## Array Attributes

Setting Random Seed

Creating 
1. 1dimsional Array
2. 2dimensional Array
3. 3dimensional Array

In [3]:
np.random.seed(34)
_1dimensional=np.random.randint(10,size=4)
_2dimensional=np.random.randint(100,size=(3,4))
_3dimensional=np.random.randint(1000,size=(4,5,6))
print(_1dimensional,_2dimensional,_3dimensional)


[1 9 6 5] [[68 35 69 11]
 [78 29 18 29]
 [89 29 20 96]] [[[830 261 916 947 531 981]
  [789 191 488 584 495 554]
  [365 468 328 894 106  77]
  [164 642 293 226 186 938]
  [203 802 361  58 702 166]]

 [[728 322 582 426 224 811]
  [213 372 543 496 724 484]
  [217 247 190 852 602 953]
  [205 428 787 618 733 238]
  [550 279 905 653 838 136]]

 [[376 350 889 100 548 874]
  [733 176 525 241   1 517]
  [986 713  99 933   0 432]
  [ 44 731 354 419 148 657]
  [326 107 487 291 934 149]]

 [[145 573 509  11 518  59]
  [589 669 959 785 991   0]
  [ 85 614 103  43 172 222]
  [945 166  23 866 890 489]
  [101 114 527 528 717 641]]]


In [4]:
print(_3dimensional.ndim)#number of dimensions of the array
print(_2dimensional.shape)#shape of the array
print(_3dimensional.size)#number of entries in the array

3
(3, 4)
120


In [5]:
print(_1dimensional.dtype)

int32


In [6]:
print("This is the size of each element in this list",_3dimensional.itemsize,"bytes")
print("This is the size of the whole list",_3dimensional.nbytes,"bytes")
#It's prety obvious that nbytes=itemsize*size attribute

This is the size of each element in this list 4 bytes
This is the size of the whole list 480 bytes


## Array Indexing: Accessing each element

Similar to the Python list accessing process 

In [7]:
_1dimensional

array([1, 9, 6, 5])

In [8]:
_1dimensional[2]

6

In [9]:
_1dimensional[-1]

5

In [10]:
_2dimensional

array([[68, 35, 69, 11],
       [78, 29, 18, 29],
       [89, 29, 20, 96]])

In [11]:
_2dimensional[2,3]

96

In [12]:
_2dimensional[-3,0]

68

In [13]:
_3dimensional[2,1,3]=171

In [14]:
_3dimensional

array([[[830, 261, 916, 947, 531, 981],
        [789, 191, 488, 584, 495, 554],
        [365, 468, 328, 894, 106,  77],
        [164, 642, 293, 226, 186, 938],
        [203, 802, 361,  58, 702, 166]],

       [[728, 322, 582, 426, 224, 811],
        [213, 372, 543, 496, 724, 484],
        [217, 247, 190, 852, 602, 953],
        [205, 428, 787, 618, 733, 238],
        [550, 279, 905, 653, 838, 136]],

       [[376, 350, 889, 100, 548, 874],
        [733, 176, 525, 171,   1, 517],
        [986, 713,  99, 933,   0, 432],
        [ 44, 731, 354, 419, 148, 657],
        [326, 107, 487, 291, 934, 149]],

       [[145, 573, 509,  11, 518,  59],
        [589, 669, 959, 785, 991,   0],
        [ 85, 614, 103,  43, 172, 222],
        [945, 166,  23, 866, 890, 489],
        [101, 114, 527, 528, 717, 641]]])

## Array Slicing

In [15]:
_1dimensional[1:4]

array([9, 6, 5])

In [16]:
_1dimensional[:3]

array([1, 9, 6])

In [17]:
_1dimensional[1:]

array([9, 6, 5])

In [18]:
_1dimensional[1:4:2]

array([9, 5])

In [19]:
_1dimensional[::2]

array([1, 6])

In [20]:
_1dimensional[::-1]#reverses the array

array([5, 6, 9, 1])

Multidimensional Slicing

In [21]:
_2dimensional

array([[68, 35, 69, 11],
       [78, 29, 18, 29],
       [89, 29, 20, 96]])

In [22]:
_2dimensional[:2,:3]

array([[68, 35, 69],
       [78, 29, 18]])

In [23]:
_3dimensional

array([[[830, 261, 916, 947, 531, 981],
        [789, 191, 488, 584, 495, 554],
        [365, 468, 328, 894, 106,  77],
        [164, 642, 293, 226, 186, 938],
        [203, 802, 361,  58, 702, 166]],

       [[728, 322, 582, 426, 224, 811],
        [213, 372, 543, 496, 724, 484],
        [217, 247, 190, 852, 602, 953],
        [205, 428, 787, 618, 733, 238],
        [550, 279, 905, 653, 838, 136]],

       [[376, 350, 889, 100, 548, 874],
        [733, 176, 525, 171,   1, 517],
        [986, 713,  99, 933,   0, 432],
        [ 44, 731, 354, 419, 148, 657],
        [326, 107, 487, 291, 934, 149]],

       [[145, 573, 509,  11, 518,  59],
        [589, 669, 959, 785, 991,   0],
        [ 85, 614, 103,  43, 172, 222],
        [945, 166,  23, 866, 890, 489],
        [101, 114, 527, 528, 717, 641]]])

In [24]:
_3dimensional[::2,1::2,::3]

array([[[789, 584],
        [164, 226]],

       [[733, 171],
        [ 44, 419]]])

Accessing Rows or Columns of a multidimensional Array

In [25]:
print(_2dimensional[:,0])#1st column

[68 78 89]


In [26]:
print(_3dimensional[:,:,0])#Think about which slice this is 

[[830 789 365 164 203]
 [728 213 217 205 550]
 [376 733 986  44 326]
 [145 589  85 945 101]]


In [27]:
print(_3dimensional[:,3,:])#Think about which slice this is 

[[164 642 293 226 186 938]
 [205 428 787 618 733 238]
 [ 44 731 354 419 148 657]
 [945 166  23 866 890 489]]


In [28]:
print(_3dimensional[:,3,2])

[293 787 354  23]


One useful so-called "feature" is that any changes made to these slices we see that have been created above would alter the main list we have with us.

In [29]:
TheNewArray=_3dimensional[:,3,:]
TheNewArray

array([[164, 642, 293, 226, 186, 938],
       [205, 428, 787, 618, 733, 238],
       [ 44, 731, 354, 419, 148, 657],
       [945, 166,  23, 866, 890, 489]])

In [30]:
TheNewArray[2,3]=6666

In [31]:
print(_3dimensional)

[[[ 830  261  916  947  531  981]
  [ 789  191  488  584  495  554]
  [ 365  468  328  894  106   77]
  [ 164  642  293  226  186  938]
  [ 203  802  361   58  702  166]]

 [[ 728  322  582  426  224  811]
  [ 213  372  543  496  724  484]
  [ 217  247  190  852  602  953]
  [ 205  428  787  618  733  238]
  [ 550  279  905  653  838  136]]

 [[ 376  350  889  100  548  874]
  [ 733  176  525  171    1  517]
  [ 986  713   99  933    0  432]
  [  44  731  354 6666  148  657]
  [ 326  107  487  291  934  149]]

 [[ 145  573  509   11  518   59]
  [ 589  669  959  785  991    0]
  [  85  614  103   43  172  222]
  [ 945  166   23  866  890  489]
  [ 101  114  527  528  717  641]]]


But sometimes it's necessary to create a copy inspite of this feature available.

In [32]:
TheNewArray=_3dimensional[:,3,:].copy()
TheNewArray[2,3]=99999
print(TheNewArray,_3dimensional)

[[  164   642   293   226   186   938]
 [  205   428   787   618   733   238]
 [   44   731   354 99999   148   657]
 [  945   166    23   866   890   489]] [[[ 830  261  916  947  531  981]
  [ 789  191  488  584  495  554]
  [ 365  468  328  894  106   77]
  [ 164  642  293  226  186  938]
  [ 203  802  361   58  702  166]]

 [[ 728  322  582  426  224  811]
  [ 213  372  543  496  724  484]
  [ 217  247  190  852  602  953]
  [ 205  428  787  618  733  238]
  [ 550  279  905  653  838  136]]

 [[ 376  350  889  100  548  874]
  [ 733  176  525  171    1  517]
  [ 986  713   99  933    0  432]
  [  44  731  354 6666  148  657]
  [ 326  107  487  291  934  149]]

 [[ 145  573  509   11  518   59]
  [ 589  669  959  785  991    0]
  [  85  614  103   43  172  222]
  [ 945  166   23  866  890  489]
  [ 101  114  527  528  717  641]]]


## Reshaping the Array

Say you want to reshape an array of length 9 into a 3*3 array

In [33]:
arrayTing=np.random.randint(100,size=9)
print(arrayTing)

[70 95  4 78 18 17 48 77 72]


In [34]:
gridTing=arrayTing.reshape((3,3))
print(gridTing)

[[70 95  4]
 [78 18 17]
 [48 77 72]]


Quite obvious that for this to work the size should becompatable with the reshaped array

There's one more way of doing this. By adding another dimension to the array. As shown this just adds another dimension to the array and does not as such reshape the array

In [35]:
x=np.array([1,2,3])
#x.reshape((1,3))
print(x.shape)

(3,)


In [38]:
print(x[:,np.newaxis])#changes the arrays shape from (3) to (3,1)
print(x[np.newaxis,:])#changes the arrays shape from (3) to (1,3)

[[1]
 [2]
 [3]]
[[1 2 3]]


In [45]:
x3d=np.arange(1000).reshape((10,10,10))
x3d.shape
x3d[:,:,np.newaxis,:].shape#Try experimenting with np.newaxis here

(10, 10, 1, 10)

In [36]:
print(x)

[1 2 3]


## Concatenation of Arrays

In [37]:
ar1=np.array([1,2,3])
ar2=np.array([3,2,1])
ar3=np.array([99,99,99])

In [38]:
np.concatenate([ar1,ar2,ar3])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [39]:
#2dimensional concatenation
ar2d1=np.array([[1,2,3],[4,5,6]])
ar2d2=np.array([[7,8,9],[10,11,12]])


In [40]:
print(np.concatenate([ar2d1,ar2d2],axis=0))#concatenate arrays along the surface axis
print(np.concatenate([ar2d1,ar2d2],axis=1))#concatenate arrays along the axis just after the sufrace axis.
#The number decides the deapth of the axis

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


What make a bit more sense are the following two functions

In [41]:
np.vstack([ar2d1,ar2d2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
np.hstack([ar2d1,ar2d2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## Splitting of arrays

In [43]:
split_ar=np.array([1,2,3,4,5,6,7,8,9])
pehla,dusra,theesra=np.split(split_ar,[3,5])
print(pehla,dusra,theesra)

[1 2 3] [4 5] [6 7 8 9]


We can split 2d arrays as well

In [44]:
grid=np.linspace(1,100,100,dtype='int64').reshape((10,10))
upper,lower=np.vsplit(grid,[5])
print(upper,lower)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]] [[ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [45]:
right,middlle,left=np.hsplit(grid,[3,7])
print(right,middlle,left)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]
 [51 52 53]
 [61 62 63]
 [71 72 73]
 [81 82 83]
 [91 92 93]] [[ 4  5  6  7]
 [14 15 16 17]
 [24 25 26 27]
 [34 35 36 37]
 [44 45 46 47]
 [54 55 56 57]
 [64 65 66 67]
 [74 75 76 77]
 [84 85 86 87]
 [94 95 96 97]] [[  8   9  10]
 [ 18  19  20]
 [ 28  29  30]
 [ 38  39  40]
 [ 48  49  50]
 [ 58  59  60]
 [ 68  69  70]
 [ 78  79  80]
 [ 88  89  90]
 [ 98  99 100]]
