In [1]:
import numpy as np

# Fancy Indexing

Fancy indexing is like the simple indexing we've already seen, but we pass arrays of indices in place of single scalars. This allows us to very quickly access and modify complicated subsets of an array's values.



In [6]:
A=np.arange(100)
A[[3,57,99]]

array([ 3, 57, 99])

The shape of the result is the shape of the index arrays rather than the actual array


In [11]:
indexes=np.array(
    [[33,44],[55,66]]
)
# REMEMBER THIS WOULD NOT WORK IF THE 2D INDEXING LIST IS A PYTHON LIST AND NOT A NUMPY ARRAY
A[indexes]

array([[33, 44],
       [55, 66]])

In [20]:
A2D=A.reshape((10,10))
row=np.array([3,4,5])
col=np.array([3,4,5])
A2D[row,col]#The elements 

array([33, 44, 55])