In [3]:
import numpy as np

# Fancy Indexing

Fancy indexing is like the simple indexing seen previously, only differing in terms of the parameters being arrays of indices in place of single scalar indeces. This allows us to very quickly access and modify complicated subsets of an array's values.



In [4]:
A=np.random.randint(100,size=100)
A[[3,57,99]]

array([53, 22, 85])

The shape of the result is the shape of the index arrays rather than the actual array


In [5]:
indexes=np.array(
    [[33,44],[55,66]]
)
# REMEMBER THIS WOULD NOT WORK IF THE 2D INDEXING LIST IS A PYTHON LIST AND NOT A NUMPY ARRAY
A[indexes]

array([[10, 54],
       [20, 95]])

In [7]:
A2D=A.reshape((10,10))
row=np.array([3,4,5])
col=np.array([3,4,5])
A2D[row,col]#The elements are A2D[3,3], A2D[4,4], A2D[5,5]

array([10, 54, 20])

The pairs row and col can be played with to include the broadcasting of arrays as follows

In [12]:
A2D=A.reshape((10,10))
row=np.array([3,4,5])
col=np.array([2,3,4,5,6])
A2D[row[:,np.newaxis],col]

array([[32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56]])

It is always important to remember with fancy indexing that the return value reflects the broadcasted shape of the indices, rather than the shape of the array being indexed.



## Combining multiple indexings

In [25]:
A2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:

A2D[3:7,[1,5,8,9]]

array([[31, 35, 38, 39],
       [41, 45, 48, 49],
       [51, 55, 58, 59],
       [61, 65, 68, 69]])

In [55]:
rows=np.arange(3,8)
colmask=np.random.randint(2,size=10,dtype='bool')

A2D[rows[:,np.newaxis],colmask]

array([[30, 33, 34, 38],
       [40, 43, 44, 48],
       [50, 53, 54, 58],
       [60, 63, 64, 68],
       [70, 73, 74, 78]])

## Modifying values of an array using Fancy Indexing

In [31]:
B=A.astype(float)
B

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [32]:
i=np.arange(40,60)
B[i]=np.linspace(0,10,20,endpoint=False)+1
B

array([ 0. ,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. ,
       11. , 12. , 13. , 14. , 15. , 16. , 17. , 18. , 19. , 20. , 21. ,
       22. , 23. , 24. , 25. , 26. , 27. , 28. , 29. , 30. , 31. , 32. ,
       33. , 34. , 35. , 36. , 37. , 38. , 39. ,  1. ,  1.5,  2. ,  2.5,
        3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,
        8.5,  9. ,  9.5, 10. , 10.5, 60. , 61. , 62. , 63. , 64. , 65. ,
       66. , 67. , 68. , 69. , 70. , 71. , 72. , 73. , 74. , 75. , 76. ,
       77. , 78. , 79. , 80. , 81. , 82. , 83. , 84. , 85. , 86. , 87. ,
       88. , 89. , 90. , 91. , 92. , 93. , 94. , 95. , 96. , 97. , 98. ,
       99. ])