In [47]:
import numpy as np
from numpy.random import randint as randi

# Array Sorting

Althought Python has it's own `sort` and `sorted` function to work with lists, We'll stick to studying `np.sort` as it turns out to be much more efficient. The `np.sort` function uses quicksort as a default sorting algorithm

In [52]:
x=randi(100,size=10)

In [56]:
np.sort(x)#RETURNS THE SORTED ARRAY. DOES NOT CHANGE THE ORIGINAL ARRAY

array([26, 35, 45, 63, 70, 77, 80, 81, 85, 99])

In [57]:
x.sort()#SORTS THE ARRAY IN PLACE

In [74]:
np.random.shuffle(x)
x

array([35, 81, 85, 80, 26, 77, 45, 63, 99, 70])

In [77]:
sortedindeces=np.argsort(x)#argsort RETURNS incedes of the sorted arrays

In [78]:
x[sortedindeces]

array([26, 35, 45, 63, 70, 77, 80, 81, 85, 99])

## Sorting along rows or columns(or any specific axis)

In [145]:
np.random.seed(11)
X3D=np.arange(1000)
np.random.shuffle(X3D)
X3D=X3D.reshape((10,10,10))
X3D

array([[[ 25, 464, 372, 730, 757, 357, 565, 767, 642, 607],
        [374,  95, 626, 400, 617, 641, 289, 340, 309, 315],
        [484, 398, 697, 521, 941, 490, 890, 522,  60, 762],
        [ 66, 747, 790, 277, 664, 738, 803, 510, 888, 352],
        [476, 500, 214, 914, 369, 513, 990, 376, 695, 121],
        [203, 431, 925, 645, 819, 442,  44, 906, 243, 482],
        [718, 104, 265, 107,  82, 742, 636, 610, 829, 911],
        [179, 123, 105, 586,  92, 863, 292, 164, 993, 530],
        [830, 424, 600,  56, 177,   2,  93, 633, 461, 864],
        [915, 306, 595, 640, 311, 700, 255, 828, 952,  87]],

       [[781, 707, 407, 691, 533, 824, 771, 731, 958,  31],
        [456, 447, 210, 189, 239, 796, 202, 591, 874, 782],
        [502, 948, 622,  46,  41, 402, 745, 542, 361, 853],
        [262, 679, 562, 896, 492, 877, 143, 201, 909, 135],
        [865, 317, 597, 282, 992, 635, 573, 625, 271, 430],
        [809, 537, 344, 999, 800, 966, 154, 355, 821,  69],
        [682, 720,  57, 293, 648, 434,

In [135]:
np.sort(X3D,axis=2)

array([[[ 25, 357, 372, 464, 565, 607, 642, 730, 757, 767],
        [ 95, 289, 309, 315, 340, 374, 400, 617, 626, 641],
        [ 60, 398, 484, 490, 521, 522, 697, 762, 890, 941],
        [ 66, 277, 352, 510, 664, 738, 747, 790, 803, 888],
        [121, 214, 369, 376, 476, 500, 513, 695, 914, 990],
        [ 44, 203, 243, 431, 442, 482, 645, 819, 906, 925],
        [ 82, 104, 107, 265, 610, 636, 718, 742, 829, 911],
        [ 92, 105, 123, 164, 179, 292, 530, 586, 863, 993],
        [  2,  56,  93, 177, 424, 461, 600, 633, 830, 864],
        [ 87, 255, 306, 311, 595, 640, 700, 828, 915, 952]],

       [[ 31, 407, 533, 691, 707, 731, 771, 781, 824, 958],
        [189, 202, 210, 239, 447, 456, 591, 782, 796, 874],
        [ 41,  46, 361, 402, 502, 542, 622, 745, 853, 948],
        [135, 143, 201, 262, 492, 562, 679, 877, 896, 909],
        [271, 282, 317, 430, 573, 597, 625, 635, 865, 992],
        [ 69, 154, 344, 355, 537, 800, 809, 821, 966, 999],
        [  4,  57, 293, 409, 434, 582,

## Partitioning

`np.partition` function takes the array `A` and an integer `K` as an argument and returns an array with `K` smallest values of `A` on the left side of the array and the rest values on the right side of it, in an arbitrary order

In [151]:
x,X3D

(array([35, 81, 85, 80, 26, 77, 45, 63, 99, 70]),
 array([[[ 25, 464, 372, 730, 757, 357, 565, 767, 642, 607],
         [374,  95, 626, 400, 617, 641, 289, 340, 309, 315],
         [484, 398, 697, 521, 941, 490, 890, 522,  60, 762],
         [ 66, 747, 790, 277, 664, 738, 803, 510, 888, 352],
         [476, 500, 214, 914, 369, 513, 990, 376, 695, 121],
         [203, 431, 925, 645, 819, 442,  44, 906, 243, 482],
         [718, 104, 265, 107,  82, 742, 636, 610, 829, 911],
         [179, 123, 105, 586,  92, 863, 292, 164, 993, 530],
         [830, 424, 600,  56, 177,   2,  93, 633, 461, 864],
         [915, 306, 595, 640, 311, 700, 255, 828, 952,  87]],
 
        [[781, 707, 407, 691, 533, 824, 771, 731, 958,  31],
         [456, 447, 210, 189, 239, 796, 202, 591, 874, 782],
         [502, 948, 622,  46,  41, 402, 745, 542, 361, 853],
         [262, 679, 562, 896, 492, 877, 143, 201, 909, 135],
         [865, 317, 597, 282, 992, 635, 573, 625, 271, 430],
         [809, 537, 344, 999, 80

In [149]:
np.partition(x,4)

array([26, 35, 45, 63, 70, 77, 80, 81, 99, 85])

In [152]:
np.partition(X3D,4,axis=2)

array([[[ 25, 357, 372, 464, 565, 607, 730, 767, 642, 757],
        [ 95, 289, 309, 315, 340, 374, 641, 400, 626, 617],
        [398,  60, 490, 484, 521, 697, 522, 762, 890, 941],
        [277,  66, 352, 510, 664, 738, 747, 790, 888, 803],
        [214, 121, 369, 376, 476, 500, 513, 695, 914, 990],
        [ 44, 243, 203, 431, 442, 482, 645, 906, 925, 819],
        [104, 265,  82, 107, 610, 636, 718, 742, 829, 911],
        [123,  92, 105, 164, 179, 863, 292, 586, 993, 530],
        [ 56,   2,  93, 177, 424, 461, 600, 633, 830, 864],
        [306,  87, 255, 311, 595, 640, 700, 828, 952, 915]],

       [[407,  31, 533, 691, 707, 731, 771, 824, 958, 781],
        [189, 202, 210, 239, 447, 456, 796, 591, 874, 782],
        [402,  41, 361,  46, 502, 948, 745, 542, 622, 853],
        [143, 135, 201, 262, 492, 562, 679, 877, 909, 896],
        [271, 282, 317, 430, 573, 597, 635, 625, 865, 992],
        [ 69, 154, 344, 355, 537, 800, 966, 999, 821, 809],
        [  4,  57, 293, 409, 434, 582,

Notice how along axis 2 (the deepest axis) all the first three elements are the smallest out of all the other elements in the list.